### ISSUE TITLE
`titleLink` provided by `typedoc.json` is always override by `mkdocs-typedoc`

### ISSUE THREAD

**Issue by studiokeywi** [JakubAndrysek/mkdocs-typedoc#3]
Due to the use of the explicit `--titleLink "/"` argument being passed to the CLI [in the plugin](https://github.com/JakubAndrysek/mkdocs-typedoc/blob/31ec60b4e4e49d4c16cdb94310be3305eefbd8b4/typedoc/plugin.py#L70), any value for `titleLink` provided by the `typedoc.json` file is ignored

As a user of this plugin, I would like my `typedoc.json` values to be used when provided instead of overridden by a magic value from the plugin, so that the output from MkDocs is consistent with the output from TypeDoc

**Comment by studiokeywi** [comment]
I suppose an alternative would be to create a plugin input for the `titleLink` value -- I'd rather keep it all in my `typedoc.json` but if it's easier to create it as an input that would be useable

**Comment by JakubAndrysek** [comment]
Hi, if you find the way how to implement it. Feel free to create the pull request. Please also update the documentation.

Thanks
Jacob

**Comment by studiokeywi** [comment]
> Hi, if you find the way how to implement it. Feel free to create the pull request. Please also update the documentation.
> 
> Thanks Jacob

I would, but I am not a Python developer, just someone trying to take advantage of the Docker image for MkDocs-Material for my Node project's documentation purposes.

I linked in the source code where I see the issue is coming from since I'm familiar with how TypeDoc works on the CLI, but I wouldn't know how to start with setting up Python/setting up this project/ensuring that my changes pass tests/etc

**Comment by JakubAndrysek** [comment]
I have implemented it. Please test it.
https://pypi.org/project/mkdocs-typedoc/1.0.3/

**Comment by JakubAndrysek** [comment]
In which project are you using this tool?

**Comment by studiokeywi** [comment]
I noticed that it has the typo of being called `tile_link` instead of `title_link` but using that as an input does the trick for me! I appreciate you being able to look into and turnaround a solution so quickly on this

This is my first time getting docs for one of my projects put together through GitHub actions -- before this, I was doing it all on my local for testing -- and it's for a chainable syntax API tool for TS/JS that I've been working on mostly for personal use but published to NPMJS

[Repo](https://github.studiokeywi.dev/papi)
[Docs Site](https://studiokeywi.github.io/papi)

**Comment by JakubAndrysek** [comment]
Thanks for describing your project and finding the typo. I have fixed it. You might upgrade to the latest version: https://pypi.org/project/mkdocs-typedoc/1.0.4/.

Have a nice day
Jacob
